/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseenrollmentsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Sono
 */
public class AddResults extends javax.swing.JFrame {

    /**
     * Creates new form AddResults
     */
    public AddResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtCom1 = new javax.swing.JTextField();
        txtCom2 = new javax.swing.JTextField();
        txtCom3 = new javax.swing.JTextField();
        txtChoose1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCom4 = new javax.swing.JTextField();
        txtChoose2 = new javax.swing.JTextField();
        txtChoose3 = new javax.swing.JTextField();
        txtChoose4 = new javax.swing.JTextField();
        txtRe1 = new javax.swing.JTextField();
        txtCr2 = new javax.swing.JTextField();
        txtCr3 = new javax.swing.JTextField();
        txtCr4 = new javax.swing.JTextField();
        txtCr5 = new javax.swing.JTextField();
        txtCr6 = new javax.swing.JTextField();
        txtCr8 = new javax.swing.JTextField();
        txtCr7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCr1 = new javax.swing.JTextField();
        txtRe2 = new javax.swing.JTextField();
        txtRe3 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtRe4 = new javax.swing.JTextField();
        txtRe5 = new javax.swing.JTextField();
        txtRe6 = new javax.swing.JTextField();
        txtRe7 = new javax.swing.JTextField();
        txtRe8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtYos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCom1.setEditable(false);

        txtCom2.setEditable(false);

        txtCom3.setEditable(false);

        txtChoose1.setEditable(false);

        jLabel4.setText("Choosed Subjects :");

        txtCom4.setEditable(false);

        txtChoose2.setEditable(false);

        txtChoose3.setEditable(false);

        txtChoose4.setEditable(false);

        jLabel1.setText("Add Student Results");

        jLabel2.setText("Compulsory Subjects :");

        jLabel3.setText("Registration Number :");

        txtRegNumber.setEditable(false);

        jLabel5.setText("Result");

        jLabel6.setText("Credits For the Subject");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel7.setText("Year of Study :");

        txtYos.setEditable(false);

        jLabel8.setText("Semester :");

        txtSemester.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRegNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(txtChoose1)
                        .addComponent(txtChoose2)
                        .addComponent(txtChoose3)
                        .addComponent(txtChoose4)
                        .addComponent(txtCom4)
                        .addComponent(txtCom3)
                        .addComponent(txtCom2)
                        .addComponent(txtCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel5)
                            .addGap(91, 91, 91))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRe2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe1)
                                .addComponent(txtRe3)
                                .addComponent(txtRe4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe6)
                                .addComponent(txtRe7)
                                .addComponent(txtRe8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addGap(63, 63, 63))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCr8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCr7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCr6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtCr5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtCr4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtCr3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtCr1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtCr2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addGap(101, 101, 101)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtYos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCr8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * method to set the values and insert data to the database
     *
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        FourthYears f = new FourthYears();  // instance to store exam details

        f.setSub1(txtCom1.getText());       // setting values
        f.setSub2(txtCom2.getText());       // setting values
        f.setSub3(txtCom3.getText());       // setting values
        f.setSub4(txtCom4.getText());       // setting values
        f.setSub5(txtChoose1.getText());    // setting values
        f.setSub6(txtChoose2.getText());    // setting values
        f.setSub7(txtChoose3.getText());    // setting values
        f.setSub8(txtChoose4.getText());    // setting values
        f.setRes1(txtRe1.getText());        // setting values
        f.setRes2(txtRe2.getText());        // setting values
        f.setRes3(txtRe3.getText());        // setting values
        f.setRes4(txtRe4.getText());        // setting values
        f.setRes5(txtRe5.getText());        // setting values
        f.setRes6(txtRe6.getText());        // setting values
        f.setRes7(txtRe7.getText());        // setting values
        f.setRes8(txtRe8.getText());        // setting values
        f.setRegNumber(txtRegNumber.getText()); // setting values
        f.setYos(txtYos.getText());         // setting values
        f.setGpa(Double.toString(calculateGPA())); // setting values
        f.setSemester(txtSemester.getText());   // setting values

        InstructorDBOperations inst = new InstructorDBOperations();                             // create a instructor db operation instance to handle backend 
        if (inst.insertResults(f)) {
            JOptionPane.showMessageDialog(this, "Submission successfull");                      // message box
            this.dispose();                                                                     // closing frame
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong. Please try again");      // message box
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * method to set values to text fields
     *
     */
    void setCompulsory(String sub[]) {
        txtCom1.setText(sub[0]);        // setting values
        txtCom2.setText(sub[1]);        // setting values
        txtCom3.setText(sub[2]);        // setting values
        txtCom4.setText(sub[3]);        // setting values
    }

    /**
     * method to set values to text fields
     *
     */
    void setChoosed(StudentSubjects sbj) {
        txtRegNumber.setText(sbj.getRegNum());  // setting values
        txtChoose1.setText(sbj.getFirst());     // setting values
        txtChoose2.setText(sbj.getSecond());    // setting values
        txtChoose3.setText(sbj.getThird());     // setting values
        txtChoose4.setText(sbj.getFourth());    // setting values
        txtYos.setText(sbj.getYos());           // setting values
        txtSemester.setText(sbj.getSemester()); // setting values
    }

    /**
     * method to calculate student's gpa
     *
     */
    double calculateGPA() {
        double gpa = 0;
        gpa = getGPV(txtRe1.getText()) * Integer.parseInt(txtCr1.getText()) + getGPV(txtRe2.getText()) * Integer.parseInt(txtCr2.getText()) + getGPV(txtRe3.getText()) * Integer.parseInt(txtCr3.getText()) + getGPV(txtRe4.getText()) * Integer.parseInt(txtCr4.getText()) + getGPV(txtRe5.getText()) * Integer.parseInt(txtCr5.getText()) + getGPV(txtRe6.getText()) * Integer.parseInt(txtCr6.getText()) + getGPV(txtRe7.getText()) * Integer.parseInt(txtCr7.getText()) + getGPV(txtRe8.getText()) * Integer.parseInt(txtCr8.getText());
        int tot = Integer.parseInt(txtCr1.getText()) + Integer.parseInt(txtCr2.getText()) + Integer.parseInt(txtCr3.getText()) + Integer.parseInt(txtCr4.getText()) + Integer.parseInt(txtCr5.getText()) + Integer.parseInt(txtCr6.getText()) + Integer.parseInt(txtCr7.getText()) + Integer.parseInt(txtCr8.getText());
        return (gpa / tot);
    }

    /**
     * method to find gpv
     *
     */
    double getGPV(String grade) {
        switch (grade) {
            case "A+":
                return 4.25;
            case "A":
                return 4.00;
            case "A-":
                return 3.75;
            case "B+":
                return 3.50;
            case "B":
                return 3.25;
            case "B-":
                return 3.00;
            case "C+":
                return 2.75;
            case "C":
                return 2.50;
            case "C-":
                return 2.25;
            case "D+":
                return 2.00;
            case "D":
                return 1.75;
            case "D-":
                return 1.50;
            default:
                return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtChoose1;
    private javax.swing.JTextField txtChoose2;
    private javax.swing.JTextField txtChoose3;
    private javax.swing.JTextField txtChoose4;
    private javax.swing.JTextField txtCom1;
    private javax.swing.JTextField txtCom2;
    private javax.swing.JTextField txtCom3;
    private javax.swing.JTextField txtCom4;
    private javax.swing.JTextField txtCr1;
    private javax.swing.JTextField txtCr2;
    private javax.swing.JTextField txtCr3;
    private javax.swing.JTextField txtCr4;
    private javax.swing.JTextField txtCr5;
    private javax.swing.JTextField txtCr6;
    private javax.swing.JTextField txtCr7;
    private javax.swing.JTextField txtCr8;
    private javax.swing.JTextField txtRe1;
    private javax.swing.JTextField txtRe2;
    private javax.swing.JTextField txtRe3;
    private javax.swing.JTextField txtRe4;
    private javax.swing.JTextField txtRe5;
    private javax.swing.JTextField txtRe6;
    private javax.swing.JTextField txtRe7;
    private javax.swing.JTextField txtRe8;
    private javax.swing.JTextField txtRegNumber;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtYos;
    // End of variables declaration//GEN-END:variables
}
