/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseenrollmentsystem;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;                                                                             // import java labraries
import javax.swing.JOptionPane;                                                                         // import java labraries

/**
 *
 * @author Sono
 */
public class StudentProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfile
     */
    ArrayList<Assignment> assingnmentList;                                                              // Array list for holding student instances
    StudentDBOperations stdOps = new StudentDBOperations();                                             // object creation for backend access
    String regNumber;                                                                                   // to identify the user
    String facultyName;                                                                                 // to stoer faculty name
    int semester;                                                                                       // to store semester 
    ArrayList<LabSession> labSessions;                                                                  // use to store the data of the lab sessions
    ArrayList<Subject> subjects;                                                                        // use to store subject result set
    ArrayList<Payment> payList;                                                                         // use to store payment details
    ArrayList<Results> resultDetails;                                                                   // use to store Results details
    ArrayList<LecturerNotes> lecNotes;

    public StudentProfileFrame() {
        initComponents();
        loadResultsTable();
        loadLecturerNotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentRegNumber = new javax.swing.JTextField();
        btnStudentLogout = new javax.swing.JButton();
        tpdStudentProfile = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssignmentTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentLabSessions = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtAmountToPay = new javax.swing.JTextField();
        btnCheckFirst = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnCheckSecond = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblResultSet = new javax.swing.JTable();
        btnDownloadResults = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtCom1 = new javax.swing.JTextField();
        txtCom2 = new javax.swing.JTextField();
        txtCom3 = new javax.swing.JTextField();
        txtChoose1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtCom4 = new javax.swing.JTextField();
        txtChoose2 = new javax.swing.JTextField();
        txtChoose3 = new javax.swing.JTextField();
        txtChoose4 = new javax.swing.JTextField();
        txtRe1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtRe2 = new javax.swing.JTextField();
        txtRe3 = new javax.swing.JTextField();
        txtRe4 = new javax.swing.JTextField();
        txtRe5 = new javax.swing.JTextField();
        txtRe6 = new javax.swing.JTextField();
        txtRe7 = new javax.swing.JTextField();
        txtRe8 = new javax.swing.JTextField();
        btnRequestResults = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLectureNotes = new javax.swing.JTable();
        btnDownloadLecNotes = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourseSubjects = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFFirstSubject = new javax.swing.JTextField();
        txtFSecondSubject = new javax.swing.JTextField();
        txtFThirdSubject = new javax.swing.JTextField();
        txtFFourthSubject = new javax.swing.JTextField();
        txtSFirstSubject = new javax.swing.JTextField();
        txtSSecondSubject = new javax.swing.JTextField();
        txtSThirdSubject = new javax.swing.JTextField();
        txtSFourthSubject = new javax.swing.JTextField();
        btnConfirmSubjects = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtUpFFir = new javax.swing.JTextField();
        txtUpFSec = new javax.swing.JTextField();
        txtUpFThi = new javax.swing.JTextField();
        txtUpFou = new javax.swing.JTextField();
        txtUpSFir = new javax.swing.JTextField();
        txtUpSSec = new javax.swing.JTextField();
        txtUpSThi = new javax.swing.JTextField();
        txtUpSFou = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnUpdateFirstSemesterSubjects = new javax.swing.JButton();
        btnUpdateSecondSemesterSubjects = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtStudentGPA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStudentFaculty = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtYoS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 248, 232));

        jLabel1.setText("User :");

        txtStudentRegNumber.setEditable(false);
        txtStudentRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentRegNumberActionPerformed(evt);
            }
        });

        btnStudentLogout.setForeground(new java.awt.Color(0, 0, 153));
        btnStudentLogout.setText("Logout");
        btnStudentLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLogoutActionPerformed(evt);
            }
        });

        tblAssignmentTable.setBackground(new java.awt.Color(232, 248, 232));
        tblAssignmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject", "Place", "Time"
            }
        ));
        jScrollPane2.setViewportView(tblAssignmentTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpdStudentProfile.addTab("Assignments", jPanel3);

        tblStudentLabSessions.setBackground(new java.awt.Color(232, 248, 232));
        tblStudentLabSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject", "Lab Name", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblStudentLabSessions);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpdStudentProfile.addTab("Lab Sessions", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Payments ");

        tblPayments.setBackground(new java.awt.Color(232, 248, 232));
        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblPayments);

        jLabel18.setText("Amount to Pay :");

        txtAmountToPay.setEditable(false);

        btnCheckFirst.setText("1st Semester");
        btnCheckFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckFirstActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(0, 0, 153));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnCheckSecond.setText("2nd Semester");
        btnCheckSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckSecondActionPerformed(evt);
            }
        });

        jLabel20.setText("Calculate");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 1235, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(jLabel20))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmountToPay, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCheckFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCheckSecond)
                                .addGap(18, 18, 18)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmountToPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(btnCheckFirst)
                    .addComponent(btnCheckSecond)
                    .addComponent(btnPay))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpdStudentProfile.addTab("Payments", jPanel5);

        tblResultSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblResultSet);

        btnDownloadResults.setText("Download Results");
        btnDownloadResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadResultsActionPerformed(evt);
            }
        });

        txtCom1.setEditable(false);

        txtCom2.setEditable(false);

        txtCom3.setEditable(false);

        txtChoose1.setEditable(false);

        jLabel33.setText("Choosed Subjects :");

        txtCom4.setEditable(false);

        txtChoose2.setEditable(false);

        txtChoose3.setEditable(false);

        txtChoose4.setEditable(false);

        txtRe1.setEditable(false);

        jLabel34.setText("Student Results");

        jLabel35.setText("Compulsory Subjects :");

        jLabel37.setText("Result");

        txtRe2.setEditable(false);

        txtRe3.setEditable(false);

        txtRe4.setEditable(false);

        txtRe5.setEditable(false);

        txtRe6.setEditable(false);

        txtRe7.setEditable(false);

        txtRe8.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35))
                    .addComponent(jLabel34))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel33)
                        .addComponent(txtChoose1)
                        .addComponent(txtChoose2)
                        .addComponent(txtChoose3)
                        .addComponent(txtChoose4)
                        .addComponent(txtCom4)
                        .addComponent(txtCom3)
                        .addComponent(txtCom2)
                        .addComponent(txtCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel37)
                            .addGap(91, 91, 91))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRe2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe1)
                                .addComponent(txtRe3)
                                .addComponent(txtRe4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRe6)
                                .addComponent(txtRe7)
                                .addComponent(txtRe8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(37, 37, 37)
                .addComponent(jLabel35)
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel37)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addComponent(jLabel33)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChoose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRe8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnRequestResults.setText("Request Results");
        btnRequestResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRequestResults, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDownloadResults, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRequestResults))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnDownloadResults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5)))
                .addGap(101, 101, 101))
        );

        tpdStudentProfile.addTab("Results", jPanel6);

        tblLectureNotes.setBackground(new java.awt.Color(232, 248, 232));
        tblLectureNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblLectureNotes);

        btnDownloadLecNotes.setText("Download");
        btnDownloadLecNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadLecNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDownloadLecNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnDownloadLecNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpdStudentProfile.addTab("Lecture Notes", jPanel11);

        tblCourseSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subjects", "Subject Code", "Semeter"
            }
        ));
        jScrollPane3.setViewportView(tblCourseSubjects);

        jLabel2.setText("Subjects belong to your course");

        jLabel3.setText("Subjects Choosing");

        jLabel4.setText("1st Semester");

        jLabel5.setText("2nd Semester");

        jLabel6.setText("1st Subject :");

        jLabel7.setText("2nd Subject :");

        jLabel8.setText("3rd Subject :");

        jLabel9.setText("4th Subject :");

        jLabel10.setText("4th Subject :");

        jLabel11.setText("3rd Subject :");

        jLabel12.setText("2nd Subject :");

        jLabel13.setText("1st Subject :");

        txtFFourthSubject.setToolTipText("");

        btnConfirmSubjects.setBackground(new java.awt.Color(0, 0, 153));
        btnConfirmSubjects.setText("Confirm");
        btnConfirmSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSubjectsActionPerformed(evt);
            }
        });

        jLabel14.setText("1st Semester");

        jLabel21.setText("Update Subjects");

        jLabel22.setText("1st Subject :");

        jLabel23.setText("2nd Subject :");

        jLabel24.setText("3rd Subject :");

        jLabel25.setText("4th Subject :");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel26.setText("2nd Semester");

        jLabel27.setText("1st Subject :");

        jLabel28.setText("2nd Subject :");

        jLabel29.setText("3rd Subject :");

        jLabel30.setText("4th Subject :");

        txtUpFSec.setToolTipText("");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnUpdateFirstSemesterSubjects.setBackground(new java.awt.Color(0, 0, 153));
        btnUpdateFirstSemesterSubjects.setText("1st Update");
        btnUpdateFirstSemesterSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFirstSemesterSubjectsActionPerformed(evt);
            }
        });

        btnUpdateSecondSemesterSubjects.setBackground(new java.awt.Color(0, 0, 153));
        btnUpdateSecondSemesterSubjects.setText("2nd Update");
        btnUpdateSecondSemesterSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSecondSemesterSubjectsActionPerformed(evt);
            }
        });

        jLabel31.setText("C: Compulsory");

        jLabel32.setText("NC: Not compulsory. You should choose 4 of them");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel32)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGap(2, 2, 2)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFFirstSubject)
                                    .addComponent(txtFSecondSubject)
                                    .addComponent(txtFThirdSubject)
                                    .addComponent(txtFFourthSubject)
                                    .addComponent(txtSFirstSubject)
                                    .addComponent(txtSSecondSubject)
                                    .addComponent(txtSThirdSubject)
                                    .addComponent(txtSFourthSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmSubjects)
                                .addGap(53, 53, 53)))))
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel25))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel26))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUpFFir)
                        .addComponent(txtUpFSec)
                        .addComponent(txtUpFThi)
                        .addComponent(txtUpFou)
                        .addComponent(txtUpSFir)
                        .addComponent(txtUpSSec)
                        .addComponent(txtUpSThi, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(txtUpSFou, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateFirstSemesterSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateSecondSemesterSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFFirstSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtUpFFir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtFSecondSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtUpFSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtFThirdSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(txtUpFThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtFFourthSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(txtUpFou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUpdateFirstSemesterSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtSFirstSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtSSecondSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtSThirdSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSFourthSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnUpdateSecondSemesterSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(txtUpSFir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel28)
                                        .addComponent(txtUpSSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel29)
                                        .addComponent(txtUpSThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel30)
                                        .addComponent(txtUpSFou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmSubjects)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1344, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        tpdStudentProfile.addTab("Subject Management", jPanel12);

        jLabel15.setText("Current GPA :");

        txtStudentGPA.setEditable(false);

        jLabel16.setText("Your Faculty :");

        txtStudentFaculty.setEditable(false);
        txtStudentFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentFacultyActionPerformed(evt);
            }
        });

        jLabel17.setText("Year of Study :");

        txtYoS.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpdStudentProfile)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStudentRegNumber)
                                    .addComponent(txtStudentGPA))))
                        .addGap(155, 155, 155)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtYoS, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStudentLogout)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentLogout)
                    .addComponent(jLabel17)
                    .addComponent(txtYoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtStudentGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtStudentFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(tpdStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * method to logout
     *
     */
    private void btnStudentLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLogoutActionPerformed
        this.dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        mf.setResizable(false);
    }//GEN-LAST:event_btnStudentLogoutActionPerformed

    /**
     * method to confirm picked subjects
     *
     */
    private void btnConfirmSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSubjectsActionPerformed

        String subjects[] = new String[8];
        subjects[0] = txtFFirstSubject.getText();
        subjects[1] = txtFSecondSubject.getText();
        subjects[2] = txtFThirdSubject.getText();
        subjects[3] = txtFFourthSubject.getText();
        subjects[4] = txtSFirstSubject.getText();
        subjects[5] = txtSSecondSubject.getText();
        subjects[6] = txtSThirdSubject.getText();
        subjects[7] = txtSFourthSubject.getText();

        String yos = txtYoS.getText();
        if (stdOps.insertSemesterSubjects(subjects, regNumber, yos)) {
            JOptionPane.showMessageDialog(this, "Subject inserted Successfully");
            txtFFirstSubject.setText("");
            txtFFourthSubject.setText("");
            txtFSecondSubject.setText("");
            txtFThirdSubject.setText("");
            txtSFirstSubject.setText("");
            txtSFourthSubject.setText("");
            txtSSecondSubject.setText("");
            txtSThirdSubject.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "You can't Insert this details now. Please contact Administrator for further information");
            txtFFirstSubject.setText("");
            txtFFourthSubject.setText("");
            txtFSecondSubject.setText("");
            txtFThirdSubject.setText("");
            txtSFirstSubject.setText("");
            txtSFourthSubject.setText("");
            txtSSecondSubject.setText("");
            txtSThirdSubject.setText("");
        }
    }//GEN-LAST:event_btnConfirmSubjectsActionPerformed

    /**
     * method to handle payment processes
     *
     */
    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed

        Payment pay = new Payment();
        pay.setPayID(0);
        pay.setAmount(txtAmountToPay.getText());
        pay.setRegNumber(txtStudentRegNumber.getText());
        pay.setCourse(facultyName);
        if (tblPayments.getRowCount() % 2 == 0) {
            pay.setSemester(1);
        } else {
            pay.setSemester(2);
        }
        pay.setYear(txtYoS.getText());

        CardDetails crdFrame = new CardDetails();
        crdFrame.setVisible(true);
        crdFrame.setCardDetails(pay);
        crdFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        crdFrame.setResizable(false);
        // listner to load table
        crdFrame.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadPaymentDetails();
                txtAmountToPay.setText("");
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtStudentRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentRegNumberActionPerformed

    }//GEN-LAST:event_txtStudentRegNumberActionPerformed

    private void txtStudentFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentFacultyActionPerformed

    }//GEN-LAST:event_txtStudentFacultyActionPerformed

    /**
     * method to calculate first semester payment
     *
     */
    private void btnCheckFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckFirstActionPerformed
        txtAmountToPay.setText(Integer.toString(stdOps.getFirstSemesterAmountToPay(regNumber, txtYoS.getText()) + 20000));
    }//GEN-LAST:event_btnCheckFirstActionPerformed

    /**
     * method to calculate second semester payment
     *
     */
    private void btnCheckSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckSecondActionPerformed
        txtAmountToPay.setText(Integer.toString(stdOps.getSecondSemesterAmountToPay(regNumber, txtYoS.getText()) + 20000));
    }//GEN-LAST:event_btnCheckSecondActionPerformed

    /**
     * method to update picked subjects
     *
     */
    private void btnUpdateFirstSemesterSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFirstSemesterSubjectsActionPerformed
        String sbjDetails[] = new String[5];

        sbjDetails[0] = regNumber;
        int semester = 1;
        sbjDetails[1] = txtUpFFir.getText();
        sbjDetails[2] = txtUpFSec.getText();
        sbjDetails[3] = txtUpFThi.getText();
        sbjDetails[4] = txtUpFou.getText();
        String yos = txtYoS.getText();

        if (stdOps.updateFirstSemesterSubjects(sbjDetails, semester, yos)) {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtUpFFir.setText("");
            txtUpFou.setText("");
            txtUpFThi.setText("");
            txtUpFSec.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Sorry, You cant update those subjects now. Contact administrator for further details");
            txtUpFFir.setText("");
            txtUpFou.setText("");
            txtUpFThi.setText("");
            txtUpFSec.setText("");
        }
    }//GEN-LAST:event_btnUpdateFirstSemesterSubjectsActionPerformed

    /**
     * method to update selected subjects
     *
     */
    private void btnUpdateSecondSemesterSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSecondSemesterSubjectsActionPerformed
        String sbjDetails[] = new String[5];

        sbjDetails[0] = regNumber;
        int semester = 2;
        sbjDetails[1] = txtUpSFir.getText();
        sbjDetails[2] = txtUpSSec.getText();
        sbjDetails[3] = txtUpSThi.getText();
        sbjDetails[4] = txtUpSFou.getText();
        String yos = txtYoS.getText();

        if (stdOps.updateSecondSemesterSubjects(sbjDetails, semester, yos)) {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtUpSFir.setText("");
            txtUpSFou.setText("");
            txtUpSThi.setText("");
            txtUpSSec.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Sorry, You cant update those subjects now. Contact administrator for further details");
            txtUpSFir.setText("");
            txtUpSFou.setText("");
            txtUpSThi.setText("");
            txtUpSSec.setText("");
        }
    }//GEN-LAST:event_btnUpdateSecondSemesterSubjectsActionPerformed

    /**
     * method to download results
     *
     */
    private void btnDownloadResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadResultsActionPerformed
        DownloadResults down = new DownloadResults();
        down.setVisible(true);
        down.setFields(resultDetails.get(tblResultSet.getSelectedRow()));
        down.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        down.setResizable(false);
    }//GEN-LAST:event_btnDownloadResultsActionPerformed

    /**
     * method to request semester results
     *
     */
    private void btnRequestResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestResultsActionPerformed
        FourthYears f = stdOps.getSemesterGPA(regNumber, semester);
        String currentGPA = stdOps.getCurrentGPA(regNumber);

        txtCom1.setText(f.getSub1());
        txtCom2.setText(f.getSub2());
        txtCom3.setText(f.getSub3());
        txtCom4.setText(f.getSub4());
        txtChoose1.setText(f.getSub5());
        txtChoose2.setText(f.getSub6());
        txtChoose3.setText(f.getSub7());
        txtChoose4.setText(f.getSub8());
        txtRe1.setText(f.getRes1());
        txtRe2.setText(f.getRes2());
        txtRe3.setText(f.getRes3());
        txtRe4.setText(f.getRes4());
        txtRe5.setText(f.getRes5());
        txtRe6.setText(f.getRes6());
        txtRe7.setText(f.getRes7());
        txtRe8.setText(f.getRes8());

        txtStudentGPA.setText(currentGPA);
        
        if(txtStudentGPA.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Sorry, Your GPA haven't calculated Yet. Please try again.");
        }
    }//GEN-LAST:event_btnRequestResultsActionPerformed

    /**
     * method to download lecturer notes
     *
     */
    private void btnDownloadLecNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadLecNotesActionPerformed
        LecturerNotes ln = lecNotes.get(tblLectureNotes.getSelectedRow());

        if (stdOps.downloadLecturerNotes(ln)) {
            JOptionPane.showMessageDialog(this, "File Download to Public Documents");
        } else {
            JOptionPane.showMessageDialog(this, "Sorry, You can't download this at this moment");
        }
    }//GEN-LAST:event_btnDownloadLecNotesActionPerformed

    /**
     * method to set student register number
     *
     */
    void setRegNumber(String regNumber) {
        this.regNumber = regNumber;
    }

    /**
     * method to set student faculty name
     *
     */
    void setFacultyName(String regNum) {
        facultyName = (stdOps.getFacultyName(regNum).getFacultyName());
        txtStudentFaculty.setText(facultyName);
        setYearOfStudy();
    }

    /**
     * method to load assignment details
     *
     */
    void loadAssignments() {
        assingnmentList = stdOps.getAssignmentList(facultyName, txtYoS.getText()); // assign the returning array list to the assignment list
        AssignmentDetails assgDetails = new AssignmentDetails(assingnmentList);
        tblAssignmentTable.setModel(assgDetails);
    }

    /**
     * method to load lab session details
     *
     */
    void loadLabSessions() {
        labSessions = stdOps.getLabSessionDetails(facultyName, txtYoS.getText());
        LabSessionDetails lbsd = new LabSessionDetails(labSessions);
        tblStudentLabSessions.setModel(lbsd);
    }

    /**
     * method to load subject details
     *
     */
    void loadSubjectDetails() {
        semester = tblPayments.getRowCount();
        subjects = stdOps.getSubjectDetails(regNumber, facultyName, txtYoS.getText());
        SubjectDetails sbjDetails = new SubjectDetails(subjects);
        tblCourseSubjects.setModel(sbjDetails);
    }

    /**
     * method to load payment details
     *
     */
    void loadPaymentDetails() {
        payList = stdOps.getPaymentDetails(regNumber);
        PaymentDetails plst = new PaymentDetails(payList);
        tblPayments.setModel(plst);

        txtStudentRegNumber.setText(regNumber);
        setYearOfStudy();
    }

    void loadLecturerNotes() {
        lecNotes = stdOps.getLecturerNotes();
        LecturerNotesDetails det = new LecturerNotesDetails(lecNotes);
        tblLectureNotes.setModel(det);
    }

    /**
     * method to calculate year of study
     *
     */
    void setYearOfStudy() {
        int year = tblPayments.getRowCount();

        switch (year) {
            case 0:
                txtYoS.setText("1 st Year");
                break;
            case 1:
                txtYoS.setText("1 st Year");
                break;
            case 2:
                txtYoS.setText("1 st Year");
                break;
            case 3:
                txtYoS.setText("2 nd Year");
                break;
            case 4:
                txtYoS.setText("2 nd Year");
                break;
            case 5:
                txtYoS.setText("3 rd Year");
                break;
            case 6:
                txtYoS.setText("3 rd Year");
                break;
            case 7:
                txtYoS.setText("4 th Year");
                break;
            case 8:
                txtYoS.setText("4 th Year");
                break;
            default:
                txtYoS.setText("Out of the Faculty");
        }

    }

    /**
     * method to load results details
     *
     */
    void loadResultsTable() {
        resultDetails = stdOps.getResultDetails();
        ResultDetails resDet = new ResultDetails(resultDetails);
        tblResultSet.setModel(resDet);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckFirst;
    private javax.swing.JButton btnCheckSecond;
    private javax.swing.JButton btnConfirmSubjects;
    private javax.swing.JButton btnDownloadLecNotes;
    private javax.swing.JButton btnDownloadResults;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnRequestResults;
    private javax.swing.JButton btnStudentLogout;
    private javax.swing.JButton btnUpdateFirstSemesterSubjects;
    private javax.swing.JButton btnUpdateSecondSemesterSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblAssignmentTable;
    private javax.swing.JTable tblCourseSubjects;
    private javax.swing.JTable tblLectureNotes;
    private javax.swing.JTable tblPayments;
    private javax.swing.JTable tblResultSet;
    private javax.swing.JTable tblStudentLabSessions;
    private javax.swing.JTabbedPane tpdStudentProfile;
    private javax.swing.JTextField txtAmountToPay;
    private javax.swing.JTextField txtChoose1;
    private javax.swing.JTextField txtChoose2;
    private javax.swing.JTextField txtChoose3;
    private javax.swing.JTextField txtChoose4;
    private javax.swing.JTextField txtCom1;
    private javax.swing.JTextField txtCom2;
    private javax.swing.JTextField txtCom3;
    private javax.swing.JTextField txtCom4;
    private javax.swing.JTextField txtFFirstSubject;
    private javax.swing.JTextField txtFFourthSubject;
    private javax.swing.JTextField txtFSecondSubject;
    private javax.swing.JTextField txtFThirdSubject;
    private javax.swing.JTextField txtRe1;
    private javax.swing.JTextField txtRe2;
    private javax.swing.JTextField txtRe3;
    private javax.swing.JTextField txtRe4;
    private javax.swing.JTextField txtRe5;
    private javax.swing.JTextField txtRe6;
    private javax.swing.JTextField txtRe7;
    private javax.swing.JTextField txtRe8;
    private javax.swing.JTextField txtSFirstSubject;
    private javax.swing.JTextField txtSFourthSubject;
    private javax.swing.JTextField txtSSecondSubject;
    private javax.swing.JTextField txtSThirdSubject;
    private javax.swing.JTextField txtStudentFaculty;
    private javax.swing.JTextField txtStudentGPA;
    private javax.swing.JTextField txtStudentRegNumber;
    private javax.swing.JTextField txtUpFFir;
    private javax.swing.JTextField txtUpFSec;
    private javax.swing.JTextField txtUpFThi;
    private javax.swing.JTextField txtUpFou;
    private javax.swing.JTextField txtUpSFir;
    private javax.swing.JTextField txtUpSFou;
    private javax.swing.JTextField txtUpSSec;
    private javax.swing.JTextField txtUpSThi;
    private javax.swing.JTextField txtYoS;
    // End of variables declaration//GEN-END:variables
}
